# Generated by Django 3.1.7 on 2021-05-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0002_userdata_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
